#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

if [[ -d "/etc/coolwsd" ]]
then
    echo "Collabora appears to already be installed"
    exit
fi

############################################ 
# Install Collabora and English spellcheck
############################################
apt install -y apt-transport-https ca-certificates
cd /usr/share/keyrings
wget https://collaboraoffice.com/downloads/gpg/collaboraonline-release-keyring.gpg
rm -f /etc/apt/sources.list.d/collaboraonline.sources
cat <<EOT >> /etc/apt/sources.list.d/collaboraonline.sources
Types: deb
URIs: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004
Suites: ./
Signed-By: /usr/share/keyrings/collaboraonline-release-keyring.gpg
EOT
apt update -y 
apt install -y coolwsd code-brand
apt install -y hunspell-en-us
coolconfig set ssl.enable false
coolconfig set ssl.termination true

# TODO: set random admin pw on initial install
#To create an administrator user and its password, you can run this command
#
#$ sudo coolconfig set-admin-password
#The output will be like this:
#
#Enter admin username [admin]:
#Enter admin password:
#Confirm admin password:
#Saving configuration to : /etc/coolwsd/coolwsd.xml …
#Saved
#

# Change Collabora port to 9990 (co-exist with multi php-fpm on HestiaCP)
file_path="/lib/systemd/system/coolwsd.service"
sed -i 's@/usr/share/coolwsd@/usr/share/coolwsd --port 9990@g' "$file_path"

