#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

if [[ -d "/etc/coolwsd" ]]
then
    echo "Collabora appears to already be installed"
    exit
fi

############################################ 
# Install Collabora and English spellcheck
############################################
apt install -y apt-transport-https ca-certificates
cd /usr/share/keyrings
wget https://collaboraoffice.com/downloads/gpg/collaboraonline-release-keyring.gpg
rm -f /etc/apt/sources.list.d/collaboraonline.sources
cat <<EOT >> /etc/apt/sources.list.d/collaboraonline.sources
Types: deb
URIs: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004
Suites: ./
Signed-By: /usr/share/keyrings/collaboraonline-release-keyring.gpg
EOT
apt update -y 
apt install -y coolwsd code-brand hunspell-en-us
coolconfig set ssl.enable false
coolconfig set ssl.termination true

# Change Collabora port to 9990 (co-exist with multi php-fpm on HestiaCP)
file_path="/lib/systemd/system/coolwsd.service"
sed -i 's@/usr/share/coolwsd@/usr/share/coolwsd --port 9990@g' "$file_path"
systemctl daemon-reload
systemctl restart coolwsd

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin Collabra "<span>&#128450;</span> Collabra plugin has finished installing."

