#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

############################################ 
# Uninstall Collabora and English spellcheck
############################################

systemctl stop coolwsd
apt remove -y inotify-tools psmisc
apt remove -y code-brand
apt remove -y collaboraofficebasis-en-us
apt remove -y collaboraoffice-dict-en
apt remove -y coolwsd
rm -f /etc/apt/sources.list.d/collaboraonline.sources
rm -rf /etc/coolwsd
rm -rf /usr/local/hestia/data/hcpp/collabora_domains
rm -f /lib/systemd/system/coolwsd.service
